SELECT BOOK.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY, sum(BOOK.PRICE * SALES) as TOTAL_SALES
FROM BOOK 
    JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID 
    JOIN BOOK_SALES ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
WHERE BOOK_SALES.SALES_DATE LIKE "2022-01%"
GROUP BY AUTHOR.AUTHOR_NAME, BOOK.CATEGORY
ORDER BY BOOK.AUTHOR_ID ASC, CATEGORY DESC