SELECT ID, CASE 
        WHEN per <= 0.25 THEN 'CRITICAL'
        WHEN per <= 0.50 THEN 'HIGH'
        WHEN per <= 0.75 THEN 'MEDIUM'
        ELSE 'LOW'
    END COLONY_NAME
FROM (SELECT ID, 
      PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) AS per
    FROM ECOLI_DATA) a
ORDER BY ID
