SELECT b.writer_id, f.NICKNAME, sum(b.PRICE) as TOTAL_SALES
FROM USED_GOODS_BOARD as b 
    JOIN USED_GOODS_USER as f 
    on b.writer_id = f.user_id
WHERE b.STATUS = "DONE"
GROUP BY b.WRITER_ID
HAVING sum(b.PRICE) >= 700000
ORDER BY TOTAL_SALES ASC